# Домашнее задание к лекции "Базовые понятия статистики"

## Обязательная часть

Будем осуществлять работу с непростым [набором данных](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv) о состоянии здоровья лошадей, испытывающих кишечные колики. 

### Задание 1. Базовое изучение

Изучить представленный набор данных на основе [описания его столбцов](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.names) и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

### Задание 2. Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

### Задание 3. Работа с пропусками

Рассчитать количество выбросов для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

## Дополнительная часть (необязательная)

Выполнить задания 1-3 для всего набора данных.

In [109]:
import pandas as pd
import numpy as np

In [110]:
df = pd.read_csv('horse_data.csv', header=None, na_values='?')
pd.options.display.max_columns = 30
# df.columns = [1 + i for i in range(28)]
df.columns = ['1: surgery', '2: Age', '3: Hospital Number', '4: rectal temperature', '5: pulse', '6: respiratory rate', 
              '7: temperature of extremities', '8: peripheral pulse', '9: mucous membranes', '10: capillary refill time',
              '11: pain', '12: peristalsis', '13: abdominal distension', '14: nasogastric tube', 
              '15: nasogastric reflux', '16: nasogastric reflux PH', '17: rectal examination - feces', 
              '18: abdomen', '19: packed cell volume', '20: total protein', '21: abdominocentesis appearance',
              '22: abdomcentesis total protein', '23: outcome', '24: surgical lesion?',
              '25: type of lesion', '26: type of lesion', '27: type of lesion', '28: cp_data']
df.head(10)

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,5: pulse,6: respiratory rate,7: temperature of extremities,8: peripheral pulse,9: mucous membranes,10: capillary refill time,11: pain,12: peristalsis,13: abdominal distension,14: nasogastric tube,15: nasogastric reflux,16: nasogastric reflux PH,17: rectal examination - feces,18: abdomen,19: packed cell volume,20: total protein,21: abdominocentesis appearance,22: abdomcentesis total protein,23: outcome,24: surgical lesion?,25: type of lesion,26: type of lesion,27: type of lesion,28: cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,5.0,4.0,4.0,NaN,NaN,NaN,3.0,5.0,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,3.0,4.0,2.0,NaN,NaN,NaN,4.0,2.0,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,1.0,1.0,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,4.0,4.0,1.0,2.0,5.0,3.0,NaN,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,NaN,3.0,3.0,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,NaN,3.0,5.0,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,NaN,4.0,2.0,2.0,1.0,NaN,3.0,4.0,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,4.0,4.0,4.0,2.0,1.0,NaN,3.0,5.0,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,5.0,3.0,1.0,2.0,1.0,NaN,3.0,NaN,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1

In [111]:
# смотрю проценты пропусков по колонкам
for col in df.columns:
    pct_missing = df[col].isnull().mean()
    print(f'{col} - {pct_missing :.1%}')

1: surgery - 0.3%
2: Age - 0.0%
3: Hospital Number - 0.0%
4: rectal temperature - 20.0%
5: pulse - 8.0%
6: respiratory rate - 19.3%
7: temperature of extremities - 18.7%
8: peripheral pulse - 23.0%
9: mucous membranes - 15.7%
10: capillary refill time - 10.7%
11: pain - 18.3%
12: peristalsis - 14.7%
13: abdominal distension - 18.7%
14: nasogastric tube - 34.7%
15: nasogastric reflux - 35.3%
16: nasogastric reflux PH - 82.3%
17: rectal examination - feces - 34.0%
18: abdomen - 39.3%
19: packed cell volume - 9.7%
20: total protein - 11.0%
21: abdominocentesis appearance - 55.0%
22: abdomcentesis total protein - 66.0%
23: outcome - 0.3%
24: surgical lesion? - 0.0%
25: type of lesion - 0.0%
26: type of lesion - 0.0%
27: type of lesion - 0.0%
28: cp_data - 0.0%

In [112]:
# смотрю на непонятные пока что мне колонки, где пропусков меньше всего
print(df['25: type of lesion'].describe())
print(df['26: type of lesion'].describe())
print(df['27: type of lesion'].describe())

count      300.000000
mean      3657.880000
std       5399.513513
min          0.000000
25%       2111.750000
50%       2673.500000
75%       3209.000000
max      41110.000000
Name: 25: type of lesion, dtype: float64
count     300.000000
mean       90.226667
std       649.569234
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      7111.000000
Name: 26: type of lesion, dtype: float64
count     300.000000
mean        7.363333
std       127.536674
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      2209.000000
Name: 27: type of lesion, dtype: float64

In [113]:
# судя по описанию, в этих столбцах вместо нулей нужно NaN забить, 
# думаю, что прямо inplace
df['25: type of lesion'].replace(0, np.nan, inplace=True)
df['26: type of lesion'].replace(0, np.nan, inplace=True)
df['27: type of lesion'].replace(0, np.nan, inplace=True)

In [114]:
df.head(50)

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,5: pulse,6: respiratory rate,7: temperature of extremities,8: peripheral pulse,9: mucous membranes,10: capillary refill time,11: pain,12: peristalsis,13: abdominal distension,14: nasogastric tube,15: nasogastric reflux,16: nasogastric reflux PH,17: rectal examination - feces,18: abdomen,19: packed cell volume,20: total protein,21: abdominocentesis appearance,22: abdomcentesis total protein,23: outcome,24: surgical lesion?,25: type of lesion,26: type of lesion,27: type of lesion,28: cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,5.0,4.0,4.0,NaN,NaN,NaN,3.0,5.0,45.0,8.4,NaN,NaN,2.0,2,11300.0,NaN,NaN,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,3.0,4.0,2.0,NaN,NaN,NaN,4.0,2.0,50.0,85.0,2.0,2.0,3.0,2,2208.0,NaN,NaN,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,1.0,1.0,33.0,6.7,NaN,NaN,1.0,2,NaN,NaN,NaN,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,4.0,4.0,1.0,2.0,5.0,3.0,NaN,48.0,7.2,3.0,5.3,2.0,1,2208.0,NaN,NaN,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,7.4,NaN,NaN,2.0,2,4300.0,NaN,NaN,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,NaN,3.0,3.0,NaN,NaN,NaN,NaN,1.0,2,NaN,NaN,NaN,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,NaN,3.0,5.0,37.0,7.0,NaN,NaN,1.0,1,3124.0,NaN,NaN,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,NaN,4.0,2.0,2.0,1.0,NaN,3.0,4.0,44.0,8.3,NaN,NaN,2.0,1,2208.0,NaN,NaN,2
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,4.0,4.0,4.0,2.0,1.0,NaN,3.0,5.0,38.0,6.2,NaN,NaN,3.0,1,3205.0,NaN,NaN,2
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,5.0,3.0,1.0,2.0,1.0,NaN,3.0,NaN,40.0,6.2,1.0,2.2,1.0,2,NaN,NaN,NaN,1
10,1.0,1,528548,38.1,66.0,12.0,3.0,3.0,5.0,1.0,3.0,3.0,1.0,2.0,1.0,3.0,2.0,5.0,44.0,6.0,2.0,3.6,1.0,1,2124.0,NaN,NaN,1
11,2.0,1,527927,39.1,72.0,52.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,4.0,4.0,50.0,7.8,NaN,NaN,1.0,1,2111.0,NaN,NaN,2
12,1.0,1,528031,37.2,42.0,12.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,1.0,NaN,4.0,5.0,NaN,7.0,NaN,NaN,1.0,2,4124.0,NaN,NaN,2
13,2.0,9,5291329,38.0,92.0,28.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,NaN,7.2,1.0,1.0,37.0,6.1,1.0,NaN,2.0,2,NaN,NaN,NaN,1
14,1.0,1,534917,38.2,76.0,28.0,3.0,1.0,1.0,1.0,3.0,4.0,1.0,2.0,2.0,NaN,4.0,4.0,46.0,81.0,1.0,2.0,1.0,1,2112.0,NaN,NaN,2
15,1.0,1,530233,37.6,96.0,48.0,3.0,1.0,4.0,1.0,5.0,3.0,3.0,2.0,3.0,4.5,4.0,NaN,45.0,6.8,NaN,NaN,2.0,1,3207.0,NaN,NaN,2
16,1.0,9,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,4.0,4.0,3.0,3.0,NaN,NaN,4.0,5.0,53.0,7.8,3.0,4.7,2.0,2,1400.0,NaN,NaN,1
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,NaN,NaN,NaN,2
18,1.0,1,5290481,37.6,64.0,21.0,1.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,1.0,NaN,2.0,5.0,40.0,7.0,1.0,NaN,1.0,1,4205.0,NaN,NaN,1
19,2.0,1,532110,39.4,110.0,35.0,4.0,3.0,6.0,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,55.0,8.7,NaN,NaN,1.0,2,NaN,NaN,NaN,2
20,1.0,1,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,5.0,4.0,4.0,3.0,1.0,NaN,4.0,4.0,46.0,6.1,2.0,NaN,1.0,1,2111.0,NaN,NaN,2
21,2.0,1,529340,38.4,48.0,16.0,1.0,NaN,1.0,1.0,1.0,3.0,1.0,2.0,3.0,5.5,4.0,3.0,49.0,6.8,NaN,NaN,1.0,2,NaN,NaN,NaN,2
22,1.0,1,521681,38.6,42.0,34.0,2.0,1.0,4.0,NaN,2.0,3.0,1.0,NaN,NaN,NaN,1.0,NaN,48.0,7.2,NaN,NaN,1.0,1,3111.0,NaN,NaN,2
23,1.0,9,534998,38.3,130.0,60.0,NaN,3.0,NaN,1.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,50.0,70.0,NaN,NaN,1.0,1,3111.0,NaN,NaN,2
24,1.0,1,533692,38.1,60.0,12.0,3.0,3.0,3.0,1.0,NaN,4.0,3.0,3.0,2.0,2.0,NaN,NaN,51.0,65.0,NaN,NaN,1.0,1,3111.0,NaN,NaN,2
25,2.0,1,529518,37.8,60.0,42.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,NaN,NaN,NaN,2
26,1.0,1,530526,38.3,72.0,30.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,1.0,NaN,3.0,5.0,43.0,7.0,2.0,3.9,1.0,1,3111.0,NaN,NaN,1
27,1.0,1,528653,37.8,48.0,12.0,3.0,1.0,1.0,1.0,NaN,3.0,2.0,1.0,1.0,NaN,1.0,3.0,37.0,5.5,2.0,1.3,1.0,2,4122.0,NaN,NaN,1
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,4300.0,NaN,NaN,2
29,2.0,1,535415,37.7,48.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,45.0,76.0,NaN,NaN,1.0,2,NaN,NaN,NaN,2
30,2.0,1,529475,37.7,96.0,30.0,3.0,3.0,4.0,2.0,5.0,4.0,4.0,3.0,2.0,4.0,4.0,5.0,66.0,7.5,NaN,NaN,2.0,1,4205.0,NaN,NaN,2
31,2.0,1,530242,37.2,108.0,12.0,3.0,3.0,4.0,2.0,2.0,4.0,2.0,NaN,3.0,6.0,3.0,3.0,52.0,8.2,3.0,7.4,3.0,1,2207.0,NaN,NaN,1
32,1.0,1,529427,37.2,60.0,NaN,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,1.0,NaN,4.0,5.0,43.0,6.6,NaN,NaN,1.0,1,2209.0,NaN,NaN,2
33,1.0,1,529663,38.2,64.0,28.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,NaN,NaN,NaN,4.0,4.0,49.0,8.6,2.0,6.6,1.0,1,2208.0,NaN,NaN,1
34,1.0,1,529796,NaN,100.0,30.0,3.0,3.0,4.0,2.0,5.0,4.0,4.0,3.0,3.0,NaN,4.0,4.0,52.0,6.6,NaN,NaN,1.0,1,1124.0,NaN,NaN,2
35,2.0,1,528812,NaN,104.0,24.0,4.0,3.0,3.0,2.0,4.0,4.0,3.0,NaN,3.0,NaN,NaN,2.0,73.0,8.4,NaN,NaN,3.0,1,7111.0,NaN,NaN,2
36,2.0,1,529493,38.3,112.0,16.0,NaN,3.0,5.0,2.0,NaN,NaN,1.0,1.0,2.0,NaN,NaN,5.0,51.0,6.0,2.0,1.0,3.0,2,5205.0,NaN,NaN,1
37,1.0,1,533847,37.8,72.0,NaN,NaN,3.0,NaN,1.0,5.0,3.0,1.0,NaN,1.0,NaN,1.0,1.0,56.0,80.0,1.0,2.0,1.0,1,3111.0,NaN,NaN,2
38,2.0,1,528996,38.6,52.0,NaN,1.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,1.0,NaN,1.0,3.0,32.0,6.6,1.0,5.0,1.0,2,NaN,NaN,NaN,1
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1,2113.0,NaN,NaN,2
40,1.0,1,529498,NaN,88.0,NaN,3.0,3.0,6.0,2.0,5.0,3.0,3.0,1.0,3.0,NaN,4.0,5.0,63.0,6.5,3.0,NaN,2.0,1,4205.0,NaN,NaN,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,8.5,NaN,0.1,1.0,1,9400.0,NaN,NaN,1
42,2.0,1,530301,38.0,60.0,12.0,3.0,1.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0,NaN,2.0,2.0,47.0,7.0,NaN,NaN,1.0,2,3111.0,NaN,NaN,2
43,1.0,1,534069,NaN,120.0,NaN,3.0,4.0,4.0,1.0,4.0,4.0,4.0,1.0,1.0,NaN,NaN,5.0,52.0,67.0,2.0,2.0,3.0,1,3205.0,NaN,NaN,2
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,4.0,4.0,NaN,2.0,1.0,NaN,NaN,5.0,57.0,69.0,3.0,2.0,3.0,1,3205.0,NaN,NaN,2
45,2.0,1,529827,NaN,120.0,NaN,4.0,3.0,4.0,2.0,5.0,4.0,4.0,1.0,1.0,NaN,4.0,5.0,60.0,6.5,3.0,NaN,2.0,1,3205.0,NaN,NaN,2
46,1.0,1,529888,37.9,60.0,15.0,3.0,NaN,4.0,2.0,5.0,4.0,4.0,2.0,2.0,NaN,4.0,5.0,65.0,7.5,NaN,NaN,1.0,1,2305.0,NaN,NaN,1
47,2.0,1,529821,37.5,48.0,16.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,37.0,6.5,NaN,NaN,1.0,2,NaN,NaN,NaN,2
48,1.0,1,528890,38.9,80.0,44.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,2.0,2.0,7.0,3.0,1.0,54.0,6.5,3.0,NaN,2.0,1,7111.0,NaN,NaN,2
49,2.0,1,529642,37.2,84.0,48.0,3.0,3.0,5.0,2.0,4.0,1.0,2.0,1.0,2.0,NaN,2.0,1.0,73.0,5.5,2.0,4.1,2.0,2,4300.0,NaN,NaN,1

In [115]:
# хочу дропнуть двадцать столбцов
# 1: surgery - 0.3% -- оставляю
# 2: Age - 0.0% -- оставляю
# 3: Hospital Number - 0.0% -- оставляю
print(df['4: rectal temperature'].describe())
# 4: rectal temperature - 20.0% -- хочу оставить, недостающие значения потом забью медианой,
#                                  т. к. все значения округлены до десятых и медиана вроде подходит

count    240.000000
mean      38.167917
std        0.732289
min       35.400000
25%       37.800000
50%       38.200000
75%       38.500000
max       40.800000
Name: 4: rectal temperature, dtype: float64

In [116]:
df.head(10)

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,5: pulse,6: respiratory rate,7: temperature of extremities,8: peripheral pulse,9: mucous membranes,10: capillary refill time,11: pain,12: peristalsis,13: abdominal distension,14: nasogastric tube,15: nasogastric reflux,16: nasogastric reflux PH,17: rectal examination - feces,18: abdomen,19: packed cell volume,20: total protein,21: abdominocentesis appearance,22: abdomcentesis total protein,23: outcome,24: surgical lesion?,25: type of lesion,26: type of lesion,27: type of lesion,28: cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,5.0,4.0,4.0,NaN,NaN,NaN,3.0,5.0,45.0,8.4,NaN,NaN,2.0,2,11300.0,NaN,NaN,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,3.0,4.0,2.0,NaN,NaN,NaN,4.0,2.0,50.0,85.0,2.0,2.0,3.0,2,2208.0,NaN,NaN,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,1.0,1.0,33.0,6.7,NaN,NaN,1.0,2,NaN,NaN,NaN,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,4.0,4.0,1.0,2.0,5.0,3.0,NaN,48.0,7.2,3.0,5.3,2.0,1,2208.0,NaN,NaN,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,7.4,NaN,NaN,2.0,2,4300.0,NaN,NaN,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,NaN,3.0,3.0,NaN,NaN,NaN,NaN,1.0,2,NaN,NaN,NaN,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,NaN,3.0,5.0,37.0,7.0,NaN,NaN,1.0,1,3124.0,NaN,NaN,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,NaN,4.0,2.0,2.0,1.0,NaN,3.0,4.0,44.0,8.3,NaN,NaN,2.0,1,2208.0,NaN,NaN,2
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,4.0,4.0,4.0,2.0,1.0,NaN,3.0,5.0,38.0,6.2,NaN,NaN,3.0,1,3205.0,NaN,NaN,2
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,5.0,3.0,1.0,2.0,1.0,NaN,3.0,NaN,40.0,6.2,1.0,2.2,1.0,2,NaN,NaN,NaN,1

In [117]:
# 5: pulse - 8.0% -- дропаю, т. к. большой разброс, непонятно, что с ним делать. может быстро меняться.
df = df.drop('5: pulse', 1)
# 6: respiratory rate - 19.3% -- дропаю, т. к. "usefulness is doubtful due to the great fluctuations"
df = df.drop('6: respiratory rate', 1)
# 7: temperature of extremities - 18.7% -- дропаю, т. к. данных мало и мне кажется они не очень полезные
df = df.drop('7: temperature of extremities', 1)
# 8: peripheral pulse - 23.0% -- дропаю методом исключения
df = df.drop('8: peripheral pulse', 1)
# 9: mucous membranes - 15.7% -- дропаю методом исключения
df = df.drop('9: mucous membranes', 1)
# 10: capillary refill time - 10.7% -- дропаю методом исключения
df = df.drop('10: capillary refill time', 1)
# 11: pain - 18.3% -- оставляю
# 12: peristalsis - 14.7% -- дропаю методом исключения
df = df.drop('12: peristalsis', 1)
# 13: abdominal distension - 18.7% -- оставляю т. к. "An IMPORTANT parameter."
# 14: nasogastric tube - 34.7% -- дропаю методом исключения
df = df.drop('14: nasogastric tube', 1)
# 15: nasogastric reflux - 35.3% -- дропаю методом исключения
df = df.drop('15: nasogastric reflux', 1)
# 16: nasogastric reflux PH - 82.3% -- дропаю, т. к. 82% значений отсутствует
df = df.drop('16: nasogastric reflux PH', 1)
# 17: rectal examination - feces - 34.0% -- дропаю методом исключения
df = df.drop('17: rectal examination - feces', 1)
# 18: abdomen - 39.3% -- дропаю методом исключения
df = df.drop('18: abdomen', 1)
# 19: packed cell volume - 9.7% -- оставляю, объективные данные, пропусков не много
# 20: total protein - 11.0% -- оставляю, объективные данные, пропусков не много
# 21: abdominocentesis appearance - 55.0% -- дропаю, т. к. 55% данных отсутствует и это не те данные, 
#                                            которые можно восстановить как мне кажется
df = df.drop('21: abdominocentesis appearance', 1)
# 22: abdomcentesis total protein - 66.0% -- т. к. это что-то специфическое и 66.0% данных отсутствует
df = df.drop('22: abdomcentesis total protein', 1)
# 23: outcome - 0.3% -- дропаю методом исключения
df = df.drop('23: outcome', 1)
# 24: surgical lesion? - 0.0% -- дропаю методом исключения
df = df.drop('24: surgical lesion?', 1)
# 25: type of lesion - 0.0% -- дропаю, т. к. муть какая-то
df = df.drop('25: type of lesion', 1)
# 26: type of lesion - 0.0% -- дропаю методом исключения
df = df.drop('26: type of lesion', 1)
# 27: type of lesion - 0.0% -- дропаю методом исключения
df = df.drop('27: type of lesion', 1)
# 28: cp_data - 0.0% -- дропаю, т. к. "this variable is of no significance"
df = df.drop('28: cp_data', 1)

In [118]:
df

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,11: pain,13: abdominal distension,19: packed cell volume,20: total protein
0,2.0,1,530101,38.5,5.0,4.0,45.0,8.4
1,1.0,1,534817,39.2,3.0,2.0,50.0,85.0
2,2.0,1,530334,38.3,3.0,1.0,33.0,6.7
3,1.0,9,5290409,39.1,2.0,4.0,48.0,7.2
4,2.0,1,530255,37.3,NaN,NaN,74.0,7.4
...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,2.0,NaN,55.0,65.0
296,2.0,1,527702,37.2,4.0,3.0,44.0,NaN
297,1.0,1,529386,37.5,4.0,3.0,60.0,6.8
298,1.0,1,530612,36.5,3.0,3.0,50.0,6.0
299,1.0,1,534618,37.2,NaN,NaN,36.0,62.0

In [119]:
df1 = df

In [120]:
# смотрю проценты пропусков по колонкам
for col in df1.columns:
    pct_missing = df[col].isnull().mean()
    print(f'{col} - {pct_missing :.1%}')

1: surgery - 0.3%
2: Age - 0.0%
3: Hospital Number - 0.0%
4: rectal temperature - 20.0%
11: pain - 18.3%
13: abdominal distension - 18.7%
19: packed cell volume - 9.7%
20: total protein - 11.0%

In [121]:
# 1: surgery -- номинальные данные
df1['1: surgery'] = df1['1: surgery'].apply(lambda x: True if x == 1 else x == False)
df1

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,11: pain,13: abdominal distension,19: packed cell volume,20: total protein
0,False,1,530101,38.5,5.0,4.0,45.0,8.4
1,True,1,534817,39.2,3.0,2.0,50.0,85.0
2,False,1,530334,38.3,3.0,1.0,33.0,6.7
3,True,9,5290409,39.1,2.0,4.0,48.0,7.2
4,False,1,530255,37.3,NaN,NaN,74.0,7.4
...,...,...,...,...,...,...,...,...
295,True,1,533886,NaN,2.0,NaN,55.0,65.0
296,False,1,527702,37.2,4.0,3.0,44.0,NaN
297,True,1,529386,37.5,4.0,3.0,60.0,6.8
298,True,1,530612,36.5,3.0,3.0,50.0,6.0
299,True,1,534618,37.2,NaN,NaN,36.0,62.0

In [122]:
df1.describe()
# 2: Age -- количественные, дискретные, выбросов нет
# 3: Hospital Number -- номинальные данные, на всякий случай в строку перевожу
df1['3: Hospital Number'] = df1['3: Hospital Number'].apply(str)

In [124]:
df1.describe()
# 4: rectal temperature -- количественные, непрерывные. пропуски забью медианой, выбросов вроде нет
df1['4: rectal temperature'] = df1['4: rectal temperature'].fillna(value=df['4: rectal temperature'].median())
# 5: 11: pain -- номинальные данные, пропуски буду считать отсутствием боли и на всякий случай 
#                в строку перевожу через int
df1['11: pain'].replace(np.nan, 1, inplace=True)
df1['11: pain'] = df1['11: pain'].apply(int)
df1['11: pain'] = df1['11: pain'].apply(str)

In [125]:
df1.describe()
# 13: abdominal distension -- качественные, порядковые. заполнять пропуски не хочу. ну или разве что модой
print(df1['13: abdominal distension'].mode())
print(df1['13: abdominal distension'].mean())
print(df1['13: abdominal distension'].median())

0    1.0
dtype: float64
2.2663934426229506
2.0

In [126]:
# 19: packed cell volume -- количественные, непрерывные. вижу, что выброс есть, но он как мне кажется,
#                           вполне может быть не ошибкой данных. пропуски наверное заполню медианой.
q1 = df1['19: packed cell volume'].quantile(0.25)
q3 = df1['19: packed cell volume'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)

print(lower_bound)
print(upper_bound)
print(df1['19: packed cell volume'].mode())
print(df1['19: packed cell volume'].mean())
print(df1['19: packed cell volume'].median())
df1['19: packed cell volume'] = df1['19: packed cell volume'].fillna(value = df1['19: packed cell volume'].median())

17.0
73.0
0    37.0
1    50.0
dtype: float64
46.29520295202952
45.0

In [127]:
# 20: total protein -- количественные, непрерывные. выбросов вроде нет.
#                      пропуски наверное заполню медианой.
q1 = df1['20: total protein'].quantile(0.25)
q3 = df1['20: total protein'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)

print(lower_bound)
print(upper_bound)
print(df1['20: total protein'].mode())
print(df1['20: total protein'].mean())
print(df1['20: total protein'].median())
df1['20: total protein'] = df1['20: total protein'].fillna(value = df1['20: total protein'].median())

-69.25
132.75
0    6.5
1    7.0
dtype: float64
24.456928838951317
7.5

In [128]:
print(df1.describe())
for col in df1.columns:
    pct_missing = df[col].isnull().mean()
    print(f'{col} - {pct_missing :.1%}')
    
df1.head(50)

           2: Age  4: rectal temperature  13: abdominal distension  \
count  300.000000             300.000000                244.000000
mean     1.640000              38.174333                  2.266393
std      2.173972               0.654831                  1.065131
min      1.000000              35.400000                  1.000000
25%      1.000000              37.900000                  1.000000
50%      1.000000              38.200000                  2.000000
75%      1.000000              38.500000                  3.000000
max      9.000000              40.800000                  4.000000

       19: packed cell volume  20: total protein
count              300.000000         300.000000
mean                46.170000          22.591667
std                  9.908584          26.453849
min                 23.000000           3.300000
25%                 39.000000           6.600000
50%                 45.000000           7.500000
75%                 50.000000          53.250000
max                 75.000000          89.000000
1: surgery - 0.0%
2: Age - 0.0%
3: Hospital Number - 0.0%
4: rectal temperature - 0.0%
11: pain - 0.0%
13: abdominal distension - 18.7%
19: packed cell volume - 0.0%
20: total protein - 0.0%

,1: surgery,2: Age,3: Hospital Number,4: rectal temperature,11: pain,13: abdominal distension,19: packed cell volume,20: total protein
0,False,1,530101,38.5,5,4.0,45.0,8.4
1,True,1,534817,39.2,3,2.0,50.0,85.0
2,False,1,530334,38.3,3,1.0,33.0,6.7
3,True,9,5290409,39.1,2,4.0,48.0,7.2
4,False,1,530255,37.3,1,NaN,74.0,7.4
5,False,1,528355,38.2,2,2.0,45.0,7.5
6,True,1,526802,37.9,3,3.0,37.0,7.0
7,True,1,529607,38.2,1,2.0,44.0,8.3
8,False,1,530051,38.2,4,4.0,38.0,6.2
9,False,9,5299629,38.3,5,1.0,40.0,6.2
10,True,1,528548,38.1,3,1.0,44.0,6.0
11,False,1,527927,39.1,2,2.0,50.0,7.8
12,True,1,528031,37.2,3,3.0,45.0,7.0
13,False,9,5291329,38.0,1,2.0,37.0,6.1
14,True,1,534917,38.2,3,1.0,46.0,81.0
15,True,1,530233,37.6,5,3.0,45.0,6.8
16,True,9,5301219,38.2,4,3.0,53.0,7.8
17,False,1,526639,37.5,1,NaN,45.0,7.5
18,True,1,5290481,37.6,2,1.0,40.0,7.0
19,False,1,532110,39.4,1,3.0,55.0,8.7
20,True,1,530157,39.9,5,4.0,46.0,6.1
21,False,1,529340,38.4,1,1.0,49.0,6.8
22,True,1,521681,38.6,2,1.0,48.0,7.2
23,True,9,534998,38.3,2,NaN,50.0,70.0
24,True,1,533692,38.1,1,3.0,51.0,65.0
25,False,1,529518,37.8,1,NaN,45.0,7.5
26,True,1,530526,38.3,3,3.0,43.0,7.0
27,True,1,528653,37.8,1,2.0,37.0,5.5
28,True,1,5279442,38.2,1,NaN,45.0,7.5
29,False,1,535415,37.7,1,1.0,45.0,76.0
30,False,1,529475,37.7,5,4.0,66.0,7.5
31,False,1,530242,37.2,2,2.0,52.0,8.2
32,True,1,529427,37.2,3,3.0,43.0,6.6
33,True,1,529663,38.2,3,NaN,49.0,8.6
34,True,1,529796,38.2,5,4.0,52.0,6.6
35,False,1,528812,38.2,4,3.0,73.0,8.4
36,False,1,529493,38.3,1,1.0,51.0,6.0
37,True,1,533847,37.8,5,1.0,56.0,80.0
38,False,1,528996,38.6,3,2.0,32.0,6.6
39,True,9,5277409,39.2,1,NaN,45.0,7.5
40,True,1,529498,38.2,5,3.0,63.0,6.5
41,False,9,5288249,39.0,1,NaN,47.0,8.5
42,False,1,530301,38.0,3,1.0,47.0,7.0
43,True,1,534069,38.2,4,4.0,52.0,67.0
44,True,1,535407,35.4,4,NaN,57.0,69.0
45,False,1,529827,38.2,5,4.0,60.0,6.5
46,True,1,529888,37.9,5,4.0,65.0,7.5
47,False,1,529821,37.5,1,1.0,37.0,6.5
48,True,1,528890,38.9,2,3.0,54.0,6.5
49,False,1,529642,37.2,4,2.0,73.0,5.5

In [129]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   1: surgery                300 non-null    bool
 1   2: Age                    300 non-null    int64
 2   3: Hospital Number        300 non-null    object
 3   4: rectal temperature     300 non-null    float64
 4   11: pain                  300 non-null    object
 5   13: abdominal distension  244 non-null    float64
 6   19: packed cell volume    300 non-null    float64
 7   20: total protein         300 non-null    float64
dtypes: bool(1), float64(4), int64(1), object(2)
memory usage: 16.8+ KB